% pathname = '/home/fran/dvs_calib/davis';
% % names = {'img1', 'img2', 'img3', 'img4', 'img5', ...
% %     'img6', 'img7', 'img8', 'img9', 'img10', ...
% %     'img11', 'img12', 'img13', 'img14', 'img15', ...
% %     'img16', 'img17', 'img18', 'img19', 'img20', ...
% %     'img21', 'img22'};
% 
% names = {'img1', 'img2', 'img3', 'img4', 'img5', ...
%     'img6', 'img7', 'img8', 'img9', 'img10', ...
%     'img11', 'img12', 'img13', 'img14', 'img15', ...
%     'img16', 'img17', 'img18', 'img19', 'img20'};
% 
% % names = {'img21', 'img22', 'img23', 'img24', 'img25', ...
% %     'img26', 'img27', 'img28', 'img29', 'img30', ...
% %     'img31', 'img32', 'img33', 'img34', 'img35', ...
% %     'img36'};
% 
% for ii=1:numel(names)
%     % get chunk of the file    
%     [frames] = getAPSframesDavisGS(fullfile(pathname, strcat(names{ii}, '.aedat')));
%     saveAllFrames(squeeze(frames(3,:,:,:)), pathname, names{ii}, 1);
% end

% pathname = '/media/fran/Seagate Backup Plus Drive/davis/pan/ptu_close_center';
% names = {'img1', 'img2', 'img3', 'img4', 'img5', ...
%     'img6', 'img7', 'img8', 'img9', 'img10', ...
%     'img11', 'img12', 'img13', 'img14', 'img15', ...
%     'img16', 'img17', 'img18', 'img19', 'img20',...
%     'img21', 'img22', 'img23', 'img24', 'img25',...
%     'img26', 'img27', 'img28', 'img29', 'img30', ...
%     'img31', 'img32', 'img33'};
% 
% for ii=1:numel(names)
%     % get chunk of the file    
%     [frames] = getAPSframesDavisGS(fullfile(pathname, strcat(names{ii}, '.aedat')));
%     saveAllFrames(squeeze(frames(3,:,:,:)), pathname, names{ii}, 1);
% end
% 
% 
% pathname = '/media/fran/Seagate Backup Plus Drive/davis/pan/ptu_close_left';
% names = {'img1', 'img2', 'img3', 'img4', 'img5', ...
%     'img6', 'img7', 'img8', 'img9', 'img10', ...
%     'img11', 'img12', 'img13', 'img14', 'img15', ...
%     'img16', 'img17', 'img18', 'img19', 'img20',...
%     'img21', 'img22', 'img23', 'img24', 'img25',...
%     'img26', 'img27', 'img28', 'img29', 'img30', ...
%     'img31', 'img32', 'img33'};
% 
% for ii=1:numel(names)
%     % get chunk of the file    
%     [frames] = getAPSframesDavisGS(fullfile(pathname, strcat(names{ii}, '.aedat')));
%     saveAllFrames(squeeze(frames(3,:,:,:)), pathname, names{ii}, 1);
% end
% 
% pathname = '/media/fran/Seagate Backup Plus Drive/davis/pan/ptu_close_right';
% names = {'img1', 'img2', 'img3', 'img4', 'img5', ...
%     'img6', 'img7', 'img8', 'img9', 'img10', ...
%     'img11', 'img12', 'img13', 'img14', 'img15', ...
%     'img16', 'img17', 'img18', 'img19', 'img20',...
%     'img21', 'img22', 'img23', 'img24', 'img25',...
%     'img26', 'img27', 'img28', 'img29', 'img30', ...
%     'img31', 'img32', 'img33'};
% 
% for ii=1:numel(names)
%     % get chunk of the file    
%     [frames] = getAPSframesDavisGS(fullfile(pathname, strcat(names{ii}, '.aedat')));
%     saveAllFrames(squeeze(frames(3,:,:,:)), pathname, names{ii}, 1);
% end

pathname = '/media/fran/Seagate Backup Plus Drive/davis/pan/ptu_far_center';
names = {'img1', 'img2', 'img3', 'img4', 'img5', ...
    'img6', 'img7', 'img8', 'img9', 'img10', ...
    'img11', 'img12', 'img13', 'img14', 'img15', ...
    'img16', 'img17', 'img18', 'img19', 'img20',...
    'img21', 'img22', 'img23', 'img24', 'img25',...
    'img26', 'img27', 'img28', 'img29', 'img30', ...
    'img31', 'img32', 'img33'};

for ii=1:numel(names)
    % get chunk of the file    
    [frames] = getAPSframesDavisGS(fullfile(pathname, strcat(names{ii}, '.aedat')));
    saveAllFrames(squeeze(frames(3,:,:,:)), pathname, names{ii}, 1);
end

pathname = '/media/fran/Seagate Backup Plus Drive/davis/pan/ptu_far_left';
names = {'img1', 'img2', 'img3', 'img4', 'img5', ...
    'img6', 'img7', 'img8', 'img9', 'img10', ...
    'img11', 'img12', 'img13', 'img14', 'img15', ...
    'img16', 'img17', 'img18', 'img19', 'img20',...
    'img21', 'img22', 'img23', 'img24', 'img25',...
    'img26', 'img27', 'img28', 'img29', 'img30', ...
    'img31', 'img32', 'img33'};

for ii=1:numel(names)
    % get chunk of the file    
    [frames] = getAPSframesDavisGS(fullfile(pathname, strcat(names{ii}, '.aedat')));
    saveAllFrames(squeeze(frames(3,:,:,:)), pathname, names{ii}, 1);
end

pathname = '/media/fran/Seagate Backup Plus Drive/davis/pan/ptu_far_right';
names = {'img1', 'img2', 'img3', 'img4', 'img5', ...
    'img6', 'img7', 'img8', 'img9', 'img10', ...
    'img11', 'img12', 'img13', 'img14', 'img15', ...
    'img16', 'img17', 'img18', 'img19', 'img20',...
    'img21', 'img22', 'img23', 'img24', 'img25',...
    'img26', 'img27', 'img28', 'img29', 'img30', ...
    'img31', 'img32', 'img33'};

for ii=1:numel(names)
    % get chunk of the file    
    [frames] = getAPSframesDavisGS(fullfile(pathname, strcat(names{ii}, '.aedat')));
    saveAllFrames(squeeze(frames(3,:,:,:)), pathname, names{ii}, 1);
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
pathname = '/media/fran/Seagate Backup Plus Drive/davis/tilt/ptu_close_center';
names = {'img1', 'img2', 'img3', 'img4', 'img5', ...
    'img6', 'img7', 'img8', 'img9', 'img10', ...
    'img11', 'img12', 'img13', 'img14', 'img15', ...
    'img16', 'img17', 'img18', 'img19', 'img20',...
    'img21', 'img22', 'img23', 'img24', 'img25',...
    'img26', 'img27', 'img28', 'img29', 'img30', ...
    'img31', 'img32', 'img33'};

for ii=1:numel(names)
    % get chunk of the file    
    [frames] = getAPSframesDavisGS(fullfile(pathname, strcat(names{ii}, '.aedat')));
    saveAllFrames(squeeze(frames(3,:,:,:)), pathname, names{ii}, 1);
end


pathname = '/media/fran/Seagate Backup Plus Drive/davis/tilt/ptu_close_left';
names = {'img1', 'img2', 'img3', 'img4', 'img5', ...
    'img6', 'img7', 'img8', 'img9', 'img10', ...
    'img11', 'img12', 'img13', 'img14', 'img15', ...
    'img16', 'img17', 'img18', 'img19', 'img20',...
    'img21', 'img22', 'img23', 'img24', 'img25',...
    'img26', 'img27', 'img28', 'img29', 'img30', ...
    'img31', 'img32', 'img33'};

for ii=1:numel(names)
    % get chunk of the file    
    [frames] = getAPSframesDavisGS(fullfile(pathname, strcat(names{ii}, '.aedat')));
    saveAllFrames(squeeze(frames(3,:,:,:)), pathname, names{ii}, 1);
end

pathname = '/media/fran/Seagate Backup Plus Drive/davis/tilt/ptu_close_right';
names = {'img1', 'img2', 'img3', 'img4', 'img5', ...
    'img6', 'img7', 'img8', 'img9', 'img10', ...
    'img11', 'img12', 'img13', 'img14', 'img15', ...
    'img16', 'img17', 'img18', 'img19', 'img20',...
    'img21', 'img22', 'img23', 'img24', 'img25',...
    'img26', 'img27', 'img28', 'img29', 'img30', ...
    'img31', 'img32', 'img33'};

for ii=1:numel(names)
    % get chunk of the file    
    [frames] = getAPSframesDavisGS(fullfile(pathname, strcat(names{ii}, '.aedat')));
    saveAllFrames(squeeze(frames(3,:,:,:)), pathname, names{ii}, 1);
end

pathname = '/media/fran/Seagate Backup Plus Drive/davis/tilt/ptu_far_center';
names = {'img1', 'img2', 'img3', 'img4', 'img5', ...
    'img6', 'img7', 'img8', 'img9', 'img10', ...
    'img11', 'img12', 'img13', 'img14', 'img15', ...
    'img16', 'img17', 'img18', 'img19', 'img20',...
    'img21', 'img22', 'img23', 'img24', 'img25',...
    'img26', 'img27', 'img28', 'img29', 'img30', ...
    'img31', 'img32', 'img33'};

for ii=1:numel(names)
    % get chunk of the file    
    [frames] = getAPSframesDavisGS(fullfile(pathname, strcat(names{ii}, '.aedat')));
    saveAllFrames(squeeze(frames(3,:,:,:)), pathname, names{ii}, 1);
end

pathname = '/media/fran/Seagate Backup Plus Drive/davis/tilt/ptu_far_left';
names = {'img1', 'img2', 'img3', 'img4', 'img5', ...
    'img6', 'img7', 'img8', 'img9', 'img10', ...
    'img11', 'img12', 'img13', 'img14', 'img15', ...
    'img16', 'img17', 'img18', 'img19', 'img20',...
    'img21', 'img22', 'img23', 'img24', 'img25',...
    'img26', 'img27', 'img28', 'img29', 'img30', ...
    'img31', 'img32', 'img33'};

for ii=1:numel(names)
    % get chunk of the file    
    [frames] = getAPSframesDavisGS(fullfile(pathname, strcat(names{ii}, '.aedat')));
    saveAllFrames(squeeze(frames(3,:,:,:)), pathname, names{ii}, 1);
end

pathname = '/media/fran/Seagate Backup Plus Drive/davis/tilt/ptu_far_right';
names = {'img1', 'img2', 'img3', 'img4', 'img5', ...
    'img6', 'img7', 'img8', 'img9', 'img10', ...
    'img11', 'img12', 'img13', 'img14', 'img15', ...
    'img16', 'img17', 'img18', 'img19', 'img20',...
    'img21', 'img22', 'img23', 'img24', 'img25',...
    'img26', 'img27', 'img28', 'img29', 'img30', ...
    'img31', 'img32', 'img33'};

for ii=1:numel(names)
    % get chunk of the file    
    [frames] = getAPSframesDavisGS(fullfile(pathname, strcat(names{ii}, '.aedat')));
    saveAllFrames(squeeze(frames(3,:,:,:)), pathname, names{ii}, 1);
end
